### ISSUE TITLE
[NFR] Console command timers support

### ISSUE THREAD

**Issue by TrogWarZ** [intaro/pinba-bundle#10]
It will be good to see timers from console commands, especially if project has many cronjobs.

But right now i see in `ScriptNameConfigureListener.php:17` that cli is strictly denied. Why? Is there any hard problem or just waiting for implementation (no comments there)?

After installing Pinba on my server, in dashboard i see cli commands as "unknown"-host and only memory stuff – will be great to see doctrine there too like in regular requests. Maybe, setting `pinba_script_name_set(gethostname())` will be informative enough?

**Comment by muxx** [comment]
Yes. But usually we configure pinba for cli separately because it depends on project.

Here is example of `app/console` file:

```php
#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

if (function_exists('pinba_server_name_set')) {
    pinba_server_name_set('job.site.ru');
}
if (function_exists('pinba_script_name_set')) {
    $argv = $_SERVER['argv'];
    $argv[0] = '/' . basename($argv[0]);
    pinba_script_name_set(implode(' ', $argv));
}

// hack for pinba for fatal errors
http_response_code(500);

/**
 * @var Composer\Autoload\ClassLoader $loader
 */
$loader = require __DIR__.'/autoload.php';

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->setAutoExit(false);
$statusCode = $application->run($input);

// hack for pinba
http_response_code($statusCode > 0 ? 500 : 200);
exit($statusCode);
```

It allows to:
1. Move console calls in separate domain in Pinboard
2. Save arguments of console calls
3. Save and notify about fails in console calls
